### ISSUE TITLE
我在尝试运行的时候报错了

### ISSUE THREAD

**Issue by m1omoe** [Secack/autorun#1]
javac autorun.java
autorun.java:1: 错误: 程序包com.alibaba.fastjson不存在
import com.alibaba.fastjson.JSONObject;
                           ^
autorun.java:2: 错误: 程序包jxl不存在
import jxl.Workbook;
          ^
autorun.java:3: 错误: 程序包jxl.write不存在
import jxl.write.*;
^
autorun.java:24: 错误: 找不到符号
            String token = JSONObject.parseObject(get(url.toString(), param.toString())).getJSONObject("Data").getString("Token");//token
                           ^
  符号:   变量 JSONObject
  位置: 类 autorun
autorun.java:28: 错误: 找不到符号
            JSONObject object = JSONObject.parseObject(get(url.toString(), "")).getJSONObject("Data");//Data
            ^
  符号:   类 JSONObject
  位置: 类 autorun
autorun.java:28: 错误: 找不到符号
            JSONObject object = JSONObject.parseObject(get(url.toString(), "")).getJSONObject("Data");//Data
                                ^
  符号:   变量 JSONObject
  位置: 类 autorun
autorun.java:30: 错误: 找不到符号
            JSONObject user = object.getJSONObject("User");
            ^
  符号:   类 JSONObject
  位置: 类 autorun
autorun.java:43: 错误: 找不到符号
            object = JSONObject.parseObject(get(url.toString(), param.toString())).getJSONObject("Data");
                     ^
  符号:   变量 JSONObject
  位置: 类 autorun
autorun.java:62: 错误: 找不到符号
        WritableWorkbook wwb;
        ^
  符号:   类 WritableWorkbook
  位置: 类 autorun
autorun.java:63: 错误: 找不到符号
        WritableSheet sheet;
        ^
  符号:   类 WritableSheet
  位置: 类 autorun
autorun.java:66: 错误: 找不到符号
            WritableFont font = new WritableFont(WritableFont.createFont("微软雅黑"), 12);
            ^
  符号:   类 WritableFont
  位置: 类 autorun
autorun.java:66: 错误: 找不到符号
            WritableFont font = new WritableFont(WritableFont.createFont("微软雅黑"), 12);
                                    ^
  符号:   类 WritableFont
  位置: 类 autorun
autorun.java:66: 错误: 找不到符号
            WritableFont font = new WritableFont(WritableFont.createFont("微软雅黑"), 12);
                                                 ^
  符号:   变量 WritableFont
  位置: 类 autorun
autorun.java:67: 错误: 找不到符号
            WritableCellFormat format = new WritableCellFormat(font);
            ^
  符号:   类 WritableCellFormat
  位置: 类 autorun
autorun.java:67: 错误: 找不到符号
            WritableCellFormat format = new WritableCellFormat(font);
                                            ^
  符号:   类 WritableCellFormat
  位置: 类 autorun
autorun.java:70: 错误: 找不到符号
                wwb = Workbook.createWorkbook(os);
                      ^
  符号:   变量 Workbook
  位置: 类 autorun
autorun.java:75: 错误: 找不到符号
                    sheet.addCell(new Label(i, 0, titles[i], format));
                                      ^
  符号:   类 Label
  位置: 类 autorun
autorun.java:80: 错误: 找不到符号
                wwb = Workbook.createWorkbook(os, Workbook.getWorkbook(os));
                                                  ^
  符号:   变量 Workbook
  位置: 类 autorun
autorun.java:80: 错误: 找不到符号
                wwb = Workbook.createWorkbook(os, Workbook.getWorkbook(os));
                      ^
  符号:   变量 Workbook
  位置: 类 autorun
autorun.java:85: 错误: 找不到符号
            sheet.addCell(new Label(0, rows, date, format));
                              ^
  符号:   类 Label
  位置: 类 autorun
autorun.java:86: 错误: 找不到符号
            sheet.addCell(new Label(1, rows, SN, format));
                              ^
  符号:   类 Label
  位置: 类 autorun
autorun.java:87: 错误: 找不到符号
            sheet.addCell(new Label(2, rows, ID, format));
                              ^
  符号:   类 Label
  位置: 类 autorun
autorun.java:88: 错误: 找不到符号
            sheet.addCell(new Label(3, rows, Class, format));
                              ^
  符号:   类 Label
  位置: 类 autorun
autorun.java:89: 错误: 找不到符号
            sheet.addCell(new Label(4, rows, nick, format));
                              ^
  符号:   类 Label
  位置: 类 autorun
autorun.java:90: 错误: 找不到符号
            sheet.addCell(new Label(5, rows, Frequency, format));
                              ^
  符号:   类 Label
  位置: 类 autorun
25 个错误
m1o@m1o-moe:~/桌面/autorun-master$

**Comment by Secack** [comment]
添加两个jar包¯\_(ツ)_/¯
